# Generated by Django 4.1 on 2022-09-14 08:52

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='profile-pics')),
                ('cawangan', models.CharField(choices=[('Choose cawangan', 'Choose cawangan'), ('PASTI SEMBULAN', 'PASTI SEMBULAN'), ('PASTI ASY SYAKIRIN', 'PASTI ASY SYAKIRIN'), ('PASTI RAUDAH', 'PASTI RAUDAH'), ('PASTI PETAGAS', 'PASTI PETAGAS'), ('PASTI CERIAMAS', 'PASTI CERIAMAS'), ('PASTI PASIR PUTIH', 'PASTI PASIR PUTIH'), ('PASTI KETIAU', 'PASTI KETIAU')], default='Choose cawangan', max_length=100)),
                ('tahunan', models.IntegerField(default=10)),
                ('sakit', models.IntegerField(default=15)),
                ('bersalin', models.IntegerField(default=60)),
                ('haji', models.IntegerField(default=46)),
                ('umrah', models.IntegerField(default=17)),
            ],
        ),
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ('-date_created',)},
        ),
        migrations.RenameField(
            model_name='application',
            old_name='requestName',
            new_name='pemohon',
        ),
        migrations.RemoveField(
            model_name='application',
            name='requestor',
        ),
        migrations.AddField(
            model_name='application',
            name='days',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='leave',
            field=models.CharField(choices=[('Pilih Cuti', 'Pilih Cuti'), ('Cuti Tahunan', 'Cuti Tahunan'), ('Cuti Sakit', 'Cuti Sakit'), ('Cuti Kecemasan', 'Cuti kecemasan'), ('Cuti Bersalin', 'Cuti Bersalin'), ('Cuti Haji', 'Cuti Haji'), ('Cuti Umrah', 'Cuti Umrah')], default='Choose Leave', max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('Approve', 'Approve'), ('Reject', 'Reject')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='application',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='details',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
