# Generated by Django 4.1 on 2022-08-29 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_cawangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cawangan',
            name='cawangan',
            field=models.CharField(choices=[('PASTI SEMBULAN', 'PASTI SEMBULAN'), ('PASTI ASY SYAKIRIN', 'PASTI ASY SYAKIRIN'), ('PASTI RAUDAH', 'PASTI RAUDAH'), ('PASTI PETAGAS', 'PASTI PETAGAS'), ('PASTI CERIAMAS', 'PASTI CERIAMAS'), ('PASTI PASIR PUTIH', 'PASTI PASIR PUTIH'), ('PASTI KETIAU', 'PASTI KETIAU')], max_length=100),
        ),
    ]
