# Generated by Django 4.0.6 on 2022-08-31 02:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_role_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.png', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[500, 300], upload_to='profile-pics'),
        ),
    ]
