# Generated by Django 4.1 on 2022-09-01 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_role_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='is_approver',
        ),
    ]
