# Generated by Django 4.0.6 on 2022-09-03 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_role_is_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
