# Generated by Django 4.1 on 2022-09-13 01:00

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_role_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default.jpg', force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[300, 300], upload_to='profile-pics'),
        ),
    ]
